--USERS
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Admin','admin@gmail.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka1','grechka@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka2','test1@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Guest','test2@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka4','test3@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka5','test4@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka6','test5@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka7','test6@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka8','test7@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka9','test8@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka10','roleuser@outlook.com','12345', TRUE);
INSERT INTO USER (NICK_NAME, EMAIL, PASSWORD, ENABLED) VALUES ('Grechka11','superuser@outlook.com','12345', TRUE);

--AUTHORITIES
INSERT INTO AUTHORITIES (USERNAME,ACCESS_GROUP) VALUES ('admin@gmail.com','ROLE_ADMIN');
INSERT INTO AUTHORITIES (USERNAME,ACCESS_GROUP) VALUES ('test1@outlook.com','ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME,ACCESS_GROUP) VALUES ('test2@outlook.com','ROLE_SUPER_USER');

--LOG
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 1');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 2');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 3');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 4');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 5');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 6');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 7');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 8');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 9');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 10');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 11');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 12');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 13');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 14');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 15');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 16');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 17');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 18');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 19');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 20');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 21');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 22');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 23');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 24');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 25');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 26');

--TEST
INSERT INTO TEST(TESTCOLUMN) VALUES('TEST COLUMN 1');
INSERT INTO TEST(TESTCOLUMN) VALUES('TEST COLUMN 2');
INSERT INTO TEST(TESTCOLUMN) VALUES('TEST COLUMN 3');
INSERT INTO TEST(TESTCOLUMN) VALUES('TEST COLUMN 4');

--POST
INSERT INTO POST(AUTHOR, TITLE, SUBTITLE, TEXT) VALUES('Admin','FIRSTTITLE','SUBTITLE','My first post!');

--COMMENT
INSERT INTO COMMENT(AUTHOR, TEXT, POST_ID) VALUES('Admin','Funny comments', '1');

